r15-team-134-master/config/routes.rb
<<<<<<< HEAD
Rails.application.routes.draw do
  resources :bids

  resources :artists
  get 'artists/new'

  resources :artworks
  get 'artworks/new'

  resources :users
  get 'users/new'

  root 'artworks#new'
  

end
=======
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  get 'items' => 'items#show'








end
>>>>>>> 63dedf9a42f2109488092f3c2f2113416a0634c3

r15-team-134-master/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :artworks, dependent: :destroy
	has_many :users, through: :artworks
	validates :name,  presence: true, length: { maximum: 50 }
	validates :title, presence: true
	validates :artwork_summary,  presence: true, length: { maximum: 250 }
	
end

r15-team-134-master/app/models/artwork.rb
class Artwork < ActiveRecord::Base
	validates :title,  presence: true, length: { maximum: 50 }
	#validates :artist, presence: true
	#validates :description,  presence: true, length: { maximum: 250 }
	#validates :media,  presence: true, length: { maximum: 50 }
	#validates :date_made,  presence: true
	#validates :dimention,  presence: true
end

r15-team-134-master/app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs :artworks
	belongs :users
	has_many :artists, through: :artworks

	validates :bid_amount,  presence: true
	validates :bid_date, presence: true
end

r15-team-134-master/app/models/user.rb
class User < ActiveRecord::Base
	has_many :artists, through: :artworks
	has_many :artworks
	has_many :bids

	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :type, presence: true
  has_secure_password  
  validates :password, presence: true, length: { minimum: 6 }   

end

r15-team-134-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

r15-team-134-master/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artists.all
  end
 
  def show
    @artist = artist.find(params[:id])
  end
 
  def new
    @artist = Artist.new
  end
 
  def edit
    @artist = Artist.find(params[:id])
  end
 
  def create
    @artist = Artist.new(artist_params)
 
    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end
  end
 
  def update
    @artist = Artist.find(params[:id])
 
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end
 
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
 
    redirect_to artists_path
  end
 
  private
    def artist_params
      params.require(:artist).permit(:name, :email, :tagline, :artworks_summary, :professional_organization, :exhibits_history,:awards_history)
    end
end

r15-team-134-master/app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @artwork = Artwork.all
  end
 
  def show
    @artwork = Artwork.find(params[:id])
  end
 
  def new
    @artwork = Artwork.new
  end
 
  def edit
    @artwork = Artwork.find(params[:id])
  end
 
  def create
    @artwork = Artwork.new(artwork_params)
 
    if @artwork.save
      redirect_to @artwork
    else
      render 'new'
    end
  end
 
  def update
    @artwork = Artwork.find(params[:id])
 
    if @artwork.update(artwork_params)
      redirect_to @artwork
    else
      render 'edit'
    end
  end
 
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
 
    redirect_to artwork_path
  end
 
  private
    def artwork_params
      params.require(:artwork).permit(:title, :artist, :description, :media, :date_made, :dimension, :suggest_price)
    end
end

r15-team-134-master/app/controllers/bids_controller.rb
class BidsController < ApplicationController
	def index
    @bids = Bid.all
  end
 
  def show
    @bid = Bid.find(params[:id])
  end
 
  def new
    @bid = Bid.new
  end
 
  def edit
    @bid= Bid.find(params[:id])
  end
 
  def create
    @bid = Bid.new(bid_params)
 
    if @bid.save
      redirect_to @bids
    else
      render 'new'
    end
  end 
 
  private
    def bid_params
      params.require(:bid).permit(:title, :time, :bid)
    end
end

r15-team-134-master/app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

r15-team-134-master/app/controllers/page_controller.rb
class PageController < ApplicationController
  def auction
  end
end

r15-team-134-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = Users.all
  end
 
  def show
    @User = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
    @user = User.find(params[:id])
  end
 
  def create
    @user = User.new(user_params)
 
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
 
  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:name, :email, :type, :password)
    end
end

r15-team-134-master/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      #welcome controller
      #index action
  end
end

r15-team-134-master/app/helpers/application_helper.rb
module ApplicationHelper
end

r15-team-134-master/app/helpers/artists_helper.rb
module ArtistsHelper
end

r15-team-134-master/app/helpers/artwork_helper.rb
module ArtworkHelper
end

r15-team-134-master/app/helpers/artworks_helper.rb
module ArtworksHelper
end

r15-team-134-master/app/helpers/bids_helper.rb
module BidsHelper
end

r15-team-134-master/app/helpers/items_helper.rb
module ItemsHelper
end

r15-team-134-master/app/helpers/page_helper.rb
module PageHelper
end

r15-team-134-master/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

r15-team-134-master/app/helpers/welcome_helper.rb
module WelcomeHelper
end

r15-team-134-master/app/views/artworks/index.html.erb
<h1>Listing artworks</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>artist_id </th>
    <th>description</th>
    <th>media</th>
    <th>date made</th>
    <th>dimension</th>
    <th>suggest</th>
     <th colspan="2"></th>
  </tr>
 
  <% @artworks.each do |artwork| %>
    <tr>
      <td><%= artwork.title %></td>
      <td><%= artwork.artist_id %></td>
      <td><%= artwork.description %></td>
      <td><%= artwork.media %></td>
      <td><%= artwork.artwork_made %></td>
      <td><%= artwork.dimension %></td>
      <td><%= artwork.suggest_price %></td>
      <td><%= link_to 'Show', artwork_path(artwork) %></td>
      <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
      </tr>
  <% end %>
</table>
  

r15-team-134-master/app/views/artworks/new.html.erb
<%= form_for @artwork do |f| %>
 
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@artwork.errors.count, "error") %> prohibited
        this artwork info from being saved:
      </h2>
      <ul>
        <% @artwork.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :artist_id %><br>
    <%= f.text_field :artist_id %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :media %><br>
    <%= f.text_field :media %>
  </p>

  <p>
    <%= f.label :date_made %><br>
    <%= f.date_field :artwork_made %>
  </p>

  <p>
    <%= f.label :dimension %><br>
    <%= f.text_field :dimension%>
  </p>

  <p>
    <%= f.label :suggest_price %><br>
    <%= f.number_field :suggest_price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%= link_to 'Back', artworks_path %>

r15-team-134-master/app/views/artworks/show.html.erb
<h1>Listing artworks</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>artist_id </th>
    <th>description</th>
    <th>media</th>
    <th>date made</th>
    <th>dimension</th>
    <th>suggest price</th>
  </tr>
    <tr>
      <td><%= @artwork.title %></td>
      <td><%= @artwork.artist_id %></td>
      <td><%= @artwork.description %></td>
      <td><%= @artwork.media %></td>
      <td><%= @artwork.artwork_made %></td>
      <td><%= @artwork.dimension %></td>
      <td><%= @artwork.suggest_price %></td>
      </tr>

</table>

<%= link_to 'Back to Arworks', artworks_path %>
<%= link_to "New Artwork", new_artwork_path %>
  

r15-team-134-master/app/views/bids/bid_show.html.erb
 <p>
    <h>Time</h>
    <%= @bid.time %>
  </p>

  <p>
    <h>bid</h>
    <%= @bid.bid %>
  </p>

r15-team-134-master/app/views/items/show.html.erb
<!-- header -->
<div class="header">
	<div class="container">
		<div class="header-main">
			<div class="logo">
				<a href="index.html"> <%= image_tag "logo.png" %> </a>
			</div>
			<div class="head-right">
			  <div class="top-nav">
					<span class="menu"> <%= image_tag "icon.png" %></span>
				<ul class="res">
					<li><a class="active" href="index.html">Home</a></li>
					<li><a href="index.html#auction">Auction</a></li>
					<li><a href="index.html#contact">Contact</a></li>
				<div class="clearfix"> </div>
				</ul>
			 </div>
		    
				
			<div class="search-box">
				<div id="sb-search" class="sb-search">
					<form>
						<input class="sb-search-input" placeholder="Search" type="search" name="search" id="search">
						<input class="sb-search-submit" type="submit" value="">
						<span class="sb-icon-search"> </span>
					</form>
			   </div>
			</div>
			<div class="clearfix"> </div>
			   <!-- search-scripts -->
			   <script src="js/classie.js"></script>
					<script src="js/uisearch.js"></script>
						<script>
							new UISearch( document.getElementById( 'sb-search' ) );
						</script>
			  <!-- //search-scripts -->
		</div>
		
		<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!-- header -->

<!-- content -->

<div class="container-fluid">
  <div class="row">
  	<div class="col-md-4"><%= image_tag "g4-.jpg" %></div>
  	<div class="col-md-8">
  		<div class="services-top">
				<h3>Title</h3>
		</div>
		<div class="caption">
			<label>Time left:</label><p style="color: red">11 min!</p>
			<label>Current bid:</label><p>$ 1,000,000</p>
			<form>
				<label>Your bid:</label><input type="text" style="width:100px" class="form-control"><br>
				<input id="submit" name="submit" type="submit" value="Place Bid" class="btn btn-primary"><br><br>
			</form>
		</div>

  	</div>
  </div>
</div>

<!-- content -->

<!-- footer -->

	<div id="footer" class="copyright2">
	<div class="container">
		<div class="copy-main">
			<div class="copy-left">
				<p>© 2015 ArTransform</p>
			</div>
			<div class="copy-right"> 
				<ul>
					<li><a class="active" href="index.html">Home</a></li>|
					<li><a href="index.html#auction">Auction</a></li>|
					<li><a href="index.html#contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<!-- footer -->

r15-team-134-master/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :type %>
      <%= select(:type, options_for_select( "Artist", "Buyer", "Admin" %>
     
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

r15-team-134-master/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

r15-team-134-master/app/views/welcome/bid.html.erb
<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :time %><br>
    <%= f.datetime_local_field :time %>
  </p>

  <p>
    <%= f.label :bid %><br>
    <%= f.number_field :bid %>
  </p>

 <p>
    <%= f.submit %>
  </p>

r15-team-134-master/app/views/welcome/index.html.erb
<!-- header -->
<div class="header">
	<div class="container">
		<div class="header-main">
			<div class="logo">
				<a href="index.html"> <%= image_tag "logo.png" %> </a>
			</div>
			<div class="head-right">
			  <div class="top-nav">
					<span class="menu"> <%= image_tag "icon.png" %></span>
				<ul class="res">
					<li><a class="active" href="index.html">Home</a></li>
					<li><a href="index.html#auction">Auction</a></li>
					<li><a href="index.html#contact">Contact</a></li>
				<div class="clearfix"> </div>
				</ul>
			 </div>
		    
				
			<div class="search-box">
				<div id="sb-search" class="sb-search">
					<form>
						<input class="sb-search-input" placeholder="Search" type="search" name="search" id="search">
						<input class="sb-search-submit" type="submit" value="">
						<span class="sb-icon-search"> </span>
					</form>
			   </div>
			</div>
			<div class="clearfix"> </div>
			   <!-- search-scripts -->
			   <script src="js/classie.js"></script>
					<script src="js/uisearch.js"></script>
						<script>
							new UISearch( document.getElementById( 'sb-search' ) );
						</script>
			  <!-- //search-scripts -->
		</div>
		
		<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!-- header -->
    
<!-- banner -->
<div class="banner">
	<div class="container">
		<div class="banner-main">
			<!-- -->
		</div>
	</div>
</div>
<div class="banner-strip">
	<div class="container">
		<h2>The Ultimate Online Arts Auction!</h2>
	   <div class="clearfix"> </div>
	</div>
</div>
<!-- banner --> 
    
<!-- Featured -->
<div class="services" id="auction">
	<div class="container">
		<div class="services-main">
			<div class="services-top">
				<h3>Featured</h3>
			</div>
			<div class="services-bottom">
				<div class="row">
					  <div class="col-sm-6 col-md-6 ser">
					<div class="thumbnail">
					  <a href="/items"><%= image_tag "g2-.jpg" %></a>
					  <div class="caption">
					    <a href="#"><h3>Praesentium voluptatum</h3></a>
					    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					  </div>
					</div>
					  </div>
					   <div class="col-sm-6 col-md-6 ser">
					<div class="thumbnail">
					  <a href="#"><%= image_tag "g3-.jpg" %></a>
					  <div class="caption">
					   <a href="#"> <h3>Accusantium doloremque</h3></a>
					    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					  </div>
					</div>
					  </div>
					   <div class="col-sm-6 col-md-6 ser">
					<div class="thumbnail">
					  <a href="#"><%= image_tag "g4-.jpg" %></a>
					  <div class="caption">
					    <a href="#"><h3>Thumbnail label</h3></a>
					    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					  </div>
					</div>
					  </div>
				  <div class="col-sm-6 col-md-6 ser">
					<div class="thumbnail">
					  <a href="#"><%= image_tag "g5-.jpg" %></a>
					  <div class="caption">
					    <a href="#"><h3>Thumbnail label</h3></a>
					    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
					  </div>
					</div>
					  </div>
				</div>
				
			</div>
		</div>
	</div>
</div>
<!-- Featured -->
    
<!-- banner strip -->

    <div class="banner-strip">
	<div class="container">
		<h2>Art is a Scream of Freedom</h2>
	   <div class="clearfix"> </div>
	</div>
    </div>
    
<!-- banner strip -->

<!-- Contact -->
    
<!-- Contact -->
    <div class="contact" id="contact">
    <div class="container">
        <div class="contact-top">
				<h3>Contact</h3>
			</div>
    <form class="form-horizontal" role="form" method="post" action="index.php">
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" value="">
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
        </div>
    </div>
    <div class="form-group">
        <label for="message" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-10">
            <textarea class="form-control" rows="4" name="message"></textarea>
        </div>
    </div>
    <div class="form-group">
        <label for="human" class="col-sm-2 control-label">2 + 3 = ?</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="human" name="human" placeholder="Your Answer">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <!-- Will be used to display an alert to the user -->
        </div>
    </div>
</form>
</div>
        </div>
<!-- footer -->

	<div class="copyright">
	<div class="container">
		<div class="copy-main">
			<div class="copy-left">
				<p>© 2015 ArTransform</p>
			</div>
			<div class="copy-right"> 
				<ul>
					<li><a class="active" href="index.html">Home</a></li>|
					<li><a href="index.html#auction">Auction</a></li>|
					<li><a href="index.html#contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<!-- footer -->